### ISSUE TITLE
Conflict with Better Rolls for 5e

### ISSUE THREAD

**Issue by InnilToo** [League-of-Foundry-Developers/foundry-token-hotbar#35]
When I select a token and hotbar (page 5 in my case) pops up the rolls from it are from a different character than the selected token. Additionally, when there are multiple tokens of the same actor on board, charges and spell slots are consumed across them instead of on the ones that made the roll.    

An example, let's say that I have an Acolyte on the board, with Bless and Cure Wounds on the hotbar. I cast Bless and one spell slot is consumed and an appropriate chat message appears with correct name of the token, all good for now. Add another Acolyte on the board and what happens is that the Acolyte 1 spell slots are reset (I did some testing without the module and consumed spell slots remained consumed if I followed the same scenario) and if I cast another spell with Acolyte 1 the message in chat and consumed slots are as if Acolyte 2 rolled.    

I did some testing, turned off and on few modules, and it appears that Token Hotbar and Better Rolls for 5e don't like each other. Without Better Rolls for 5e it seems to be working as intended. If I were to guess I think it has something to do with how Better Rolls for 5e creates macros.

Token Hotbar version 4.2.0
Better Rolls for 5e version 1.2.1
Foundry version 0.7.8 (was happening on 0.7.7 as well)
DnD5e system version 1.1.1

**Comment by MrVauxs** [comment]
Please Note that Better Rolls is [incompatible](https://github.com/RedReign/FoundryVTT-BetterRolls5e/issues/175) with 1.2.X of dnd5e as of yet.

**Comment by InnilToo** [comment]
Any news on this? It still behaves weirdly, sometimes even showing macros that the actor does not have, transferring them between tokens. And resources are also consumed on the wrong actor. Bunch of weird stuff going on but I am still hoping.

Last tested on Foundry 0.8.6

**Comment by janssen-io** [comment]
Unfortunately this module is no longer under active development. This issue might be resolved if another developer in the community wants to pick it up. 

Apologies for the inconvenience. :(

**Comment by janssen-io** [comment]
@InnilToo the revamped version of the module is available for testing: https://github.com/janssen-io/foundry-tokenhotbar-js

Nothing in particular was changed with regards to this issue, but you might find it works better.

**Comment by InnilToo** [comment]
Thank you for the update! I tested it and unfortunately the behavior persists.
I had to decrease the "minimumCoreVersion": "9" to 0.8.9 as that is the highest version available on Forge.
