### ISSUE TITLE
Incompatability with 0.8.8 version of foundry, any chance we'll see an update?

### ISSUE THREAD

**Issue by ScaredBehr** [League-of-Foundry-Developers/foundry-token-hotbar#43]
Recently updated to 0.8.X (went from 0.7.10 to 0.8.8) and getting a few errors from token hotbar. I love using this module so im hoping its not been abandoned. 

Error that appears when selecting a token on the canvas

![FoundryVTT_Znqejo2DwJ](https://user-images.githubusercontent.com/84649678/124407046-f257fd00-dd10-11eb-8d7e-652b49827d4f.png)

Console Log when selecting a token on the canvas

![FoundryVTT_aMWcblIbyq](https://user-images.githubusercontent.com/84649678/124407072-07cd2700-dd11-11eb-80be-e22dba7955a2.png)

Hoping its maybe something on my end and is a simple fix. Tested with other modules disabled.

**Comment by Bobsson** [comment]
It's not just you, @ScaredBehr. I just found this module and it should solve a problem I was having... but I'm having the same problems you are.

**Comment by radoslawg** [comment]
Same boat here. This sounds like a such a useful module. I tried looking through source code but I have no idea what's going on ;)

**Comment by janssen-io** [comment]
Old dev here: unfortunately I couldn’t keep up with the development pace of Foundry.

If anyone wants to take a stab at it, I’d be happy to answer any questions or provide some guidance.

**Comment by radoslawg** [comment]
> Old dev here: unfortunately I couldn’t keep up with the development pace of Foundry.
> 
> If anyone wants to take a stab at it, I’d be happy to answer any questions or provide some guidance.

I kinda fixed it. But because I have little experience with foundry (and Typescript/javascript is not what I use every day) I don't know what else I broke. ;) I will post Pull Request anyway.

Also, for everybody interested. If you use this module with conjuction with Custom Hotbar then it seems to work. Just configure this module to use Custom Hotbar instead of Foundry Hotbar.
