### ISSUE TITLE
Token Hotbar cannot be installed

### ISSUE THREAD

**Issue by apoapostolov** [League-of-Foundry-Developers/foundry-token-hotbar#45]
![image](https://user-images.githubusercontent.com/4083812/126692407-8896ce7c-daaf-49bf-8296-f41465e70ce7.png)

Also the zip seems to lack main folder, and AFAIK the folder must be all noncapitalized, but the id of the module (which afaik is same as folder) is camel-case.

**Comment by Luthervian** [comment]
I am having this error as well.

**Comment by Doresain** [comment]
Installing from the module.json link here in the repo works just fine, it's only broken via the Foundry module browser.

The other issues you mention are red herrings - no main folder is needed since TokenHotbar.js looks to be concatenated on release and while lowercase is standard Foundry can handle capitalized folders just fine.

**Comment by Foxaramar** [comment]
It doesn't work from the module.json link in the repo either for me

**Comment by janssen-io** [comment]
Aha, I see the issue. When I transferred the repository to the league, I forgot to adjust the url in the manifest. It still refers to the location on my account. I’ll fix it later today.

> https://play.google.com/store/apps/details?id=com.github.android&utm_campaign=notification-email

**Comment by janssen-io** [comment]
I updated the module.json with the correct link to the release.
Can you guys test if it works again? :)

**Comment by stevenoftheages** [comment]
This is the link that works (in the module.json): https://github.com/League-of-Foundry-Developers/foundry-token-hotbar/releases/download/v4.2.2/module.json

Attempting to install from the module browser without _this_ manfest results in the same error.

**Comment by janssen-io** [comment]
I forgot to update the module in the Foundry admin panel, it points to an existing module.json now. :)

**Comment by stevenoftheages** [comment]
Excellent! So happy to see this module on 8.x, it's one of my all-time must-haves! Thanks Stan :)

**Comment by janssen-io** [comment]
Good to hear. I’m afraid it still has some other unresolved issues. :( 

So for now I’ll close this one, unless someone still has issues with the installer.
