### ISSUE TITLE
Hotbar not emptied when selecting new token

### ISSUE THREAD

**Issue by Arkandos** [League-of-Foundry-Developers/foundry-token-hotbar#46]
The token hotbar does not empty when selecting a new unlinked token, or deselecting.

This results in the module being unusable, as it creates a mishmash of all the macros you have previously selected.

Foundry 0.8.8 and Token Hotbar 4.2.2

**Comment by janssen-io** [comment]
Thanks for the bug report, Arkandos.

I'm currently working on a new version that's compatible with the Foundry v0.9.0.
It's far from done, but the basic functionality of swapping out the bar seems to be more stable already.
