### ISSUE TITLE
Persistent Macros 

### ISSUE THREAD

**Issue by AlexJPF** [League-of-Foundry-Developers/foundry-token-hotbar#50]
Macros stick around when removed (right click, remove). They disappear until you deselect and reselect the token; then that macro is back. Deleting the macro actually removes it, but that's not really a workaround.

Foundry 0.8.9
Token Hotbar 4.2.2

**Comment by janssen-io** [comment]
Hi Alex, thanks for the bug report. This issue will be fixed in the revamped Token Hotbar.
More info here: https://github.com/janssen-io/foundry-tokenhotbar-js
